#!/bin/bash
# Takes in a date range as arguments and searches for files missing, then writes those missing dates to a file
# Does not include the date at the end of the range
startdate=$1
enddate=$2
dates=$1
while (($dates != $enddate))
do 
	file=nh_16to32_$dates
	if ! [[ -f $file ]]
	then
		echo $dates >> missing_dates
	fi
	dates="$(date +%Y%m%d -d "$dates + 1 days")"
done